apiVersion: v1
kind: Pod 
metadata:
  name: storage-pod
spec:
  containers:
    - name: test
      image: debian
      command: ["/bin/bash", "-ec", "while :; do sleep 2; done"]
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: storage-pvc
